### ISSUE TITLE
TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by BhagyeshVikani** [nturley/netlistsvg#83]
I am getting this while running `netlistsvg test.json -o test.svg --skin test_skin.svg`.
```
TypeError: Cannot read property 'x' of undefined
    at /usr/local/lib/node_modules/netlistsvg/built/drawModule.js:160:20
    at Array.map (<anonymous>)
    at _loop_1 (/usr/local/lib/node_modules/netlistsvg/built/drawModule.js:159:12)
    at removeDummyEdges (/usr/local/lib/node_modules/netlistsvg/built/drawModule.js:185:23)
    at Object.drawModule [as default] (/usr/local/lib/node_modules/netlistsvg/built/drawModule.js:19:5)
    at /usr/local/lib/node_modules/netlistsvg/built/index.js:25:57
    at <anonymous>
```

**Comment by amstan** [comment]
This can be closed.
